source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PXWebSnapshot', :exclusive => true do
  pod "PXWebSnapshot", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXWebSnapshot", :path => "../"


end
